### ISSUE TITLE
validate puppet plans

### ISSUE THREAD

**Issue by vchepkov** [chriskuehl/puppet-pre-commit-hooks#15]
puppet parser validate has a special flag - `--tasks` to validate puppet plans, which are usually under plans/ folder

It seems puppet-validate expects arguments to be in `--arg=value` format, so one can't easily pass `--task` argument, instead

**Comment by aerickson** [comment]
A temporary workaround is to exclude the plans directories.

```
- repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
  rev: v2.1.0
  hooks:
  - id: puppet-validate
    exclude: '^modules/\w+/plans'
```
